# Generated by Django 5.2.8 on 2025-11-26 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('mag_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=' ', max_length=50)),
                ('email', models.CharField(default=' ', max_length=50)),
                ('password', models.CharField(default=' ', max_length=50)),
            ],
        ),
    ]
