# Generated by Django 5.2.8 on 2025-11-27 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orders_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='updateorders',
            fields=[
                ('update_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_id', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=5000)),
                ('tiem_stamp', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
